name: 'Get the Green client'
description: 'Coding your teams norms and analyze your code to get important metrics'
inputs:
  co-repo-key:
    description: 'The Code Observability repository key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.co-repo-key }}

branding:
  icon: 'check-circle'
  color: 'green'
